site_name: Gertrude Docs

nav:
    - Home: index.md
    - Getting Started:
        - For Non-Tech People: getting-started-non-tech.md
        - For tech people: getting-started-tech.md
        - Collaboration + Workflow: collaboration-workflow.md
    - Editing & Encoding: editing.md
    - Developing & Designing: developing.md
    - Syllabus: https://mackenziekbrooks.github.io/dci295D-f23-digitaleditions/


theme: 
  name: mkdocs
  highlightjs: true
  hljs_languages:
        - yaml
        - bash
        - css
        - javascript
        - markdown
        - ruby
        - html
        - xml

extra_css: 
  - css/extra.css
